# coding: utf-8

"""
    Layered Insight Scan

    Layered Insight Scan performs static vulnerability analysis, license and package compliance.  You can find out more about Scan at http://layeredinsight.com.

    OpenAPI spec version: 0.9.2
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_scan_api
from layint_scan_api.rest import ApiException
from layint_scan_api.apis.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """ TagsApi unit test stubs """

    def setUp(self):
        self.api = layint_scan_api.apis.tags_api.TagsApi()

    def tearDown(self):
        pass

    def test_add_tag(self):
        """
        Test case for add_tag

        Add a tag
        """
        pass

    def test_delete_tag(self):
        """
        Test case for delete_tag

        Delete a tag by ID
        """
        pass

    def test_get_tag(self):
        """
        Test case for get_tag

        Get a tag by ID
        """
        pass

    def test_get_tags(self):
        """
        Test case for get_tags

        List all tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
