# coding: utf-8

"""
    Layered Insight Scan

    Layered Insight Scan performs static vulnerability analysis, license and package compliance.  You can find out more about Scan at http://layeredinsight.com.

    OpenAPI spec version: 0.9.4
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_scan_api
from layint_scan_api.rest import ApiException
from layint_scan_api.apis.license_api import LicenseApi


class TestLicenseApi(unittest.TestCase):
    """ LicenseApi unit test stubs """

    def setUp(self):
        self.api = layint_scan_api.apis.license_api.LicenseApi()

    def tearDown(self):
        pass

    def test_license_get(self):
        """
        Test case for license_get

        Get application license information
        """
        pass

    def test_update_license(self):
        """
        Test case for update_license

        Add or update application license
        """
        pass


if __name__ == '__main__':
    unittest.main()
