# coding: utf-8

"""
    Layered Insight Scan

    Layered Insight Scan performs static vulnerability analysis, license and package compliance.  You can find out more about Scan at http://layeredinsight.com.

    OpenAPI spec version: 0.9.2
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_scan_api
from layint_scan_api.rest import ApiException
from layint_scan_api.apis.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """ AnalyticsApi unit test stubs """

    def setUp(self):
        self.api = layint_scan_api.apis.analytics_api.AnalyticsApi()

    def tearDown(self):
        pass

    def test_cve_search(self):
        """
        Test case for cve_search

        Searches image scan results for specified CVE ID
        """
        pass

    def test_get_stats(self):
        """
        Test case for get_stats

        Gets vulnerability statistics for user's images
        """
        pass

    def test_package_search(self):
        """
        Test case for package_search

        Searches for images with a specified software package
        """
        pass

    def test_top_cves(self):
        """
        Test case for top_cves

        Returns a list of most common/severe vulnerabilities present in a users images
        """
        pass

    def test_top_vuln_images(self):
        """
        Test case for top_vuln_images

        Returns a list of most vulnerable images
        """
        pass


if __name__ == '__main__':
    unittest.main()
