# coding: utf-8

"""
    Layered Insight Scan

    Layered Insight Scan performs static vulnerability analysis, license and package compliance.  You can find out more about Scan at http://layeredinsight.com.

    OpenAPI spec version: 0.9.2
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_scan_api
from layint_scan_api.rest import ApiException
from layint_scan_api.apis.images_api import ImagesApi


class TestImagesApi(unittest.TestCase):
    """ ImagesApi unit test stubs """

    def setUp(self):
        self.api = layint_scan_api.apis.images_api.ImagesApi()

    def tearDown(self):
        pass

    def test_add_image(self):
        """
        Test case for add_image

        Submit an image name for scanning
        """
        pass

    def test_delete_image(self):
        """
        Test case for delete_image

        Delete specified image
        """
        pass

    def test_get_image(self):
        """
        Test case for get_image

        Get image details
        """
        pass

    def test_get_image_compliance(self):
        """
        Test case for get_image_compliance

        Get compliance report for specified image
        """
        pass

    def test_get_image_scan(self):
        """
        Test case for get_image_scan

        Get scan data for specific scan for specified image
        """
        pass

    def test_get_image_scans(self):
        """
        Test case for get_image_scans

        Get all scan data for specified image
        """
        pass

    def test_get_images(self):
        """
        Test case for get_images

        Get list of scanned images
        """
        pass

    def test_is_image_compliant(self):
        """
        Test case for is_image_compliant

        Determines if specified image is in compliance with policies applied to image
        """
        pass


if __name__ == '__main__':
    unittest.main()
