# coding: utf-8

"""
    Layered Insight Scan

    Layered Insight Scan performs static vulnerability analysis, license and package compliance.  You can find out more about Scan at http://layeredinsight.com.

    OpenAPI spec version: 0.9.4
    Contact: help@layeredinsight.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import layint_scan_api
from layint_scan_api.rest import ApiException
from layint_scan_api.apis.clair_api import ClairApi


class TestClairApi(unittest.TestCase):
    """ ClairApi unit test stubs """

    def setUp(self):
        self.api = layint_scan_api.apis.clair_api.ClairApi()

    def tearDown(self):
        pass

    def test_clair_update(self):
        """
        Test case for clair_update

        Notify user(s) of vulnerability update from clair notification
        """
        pass

    def test_get_clair_updates(self):
        """
        Test case for get_clair_updates

        Returns date/time estimation when clair updates will be done
        """
        pass


if __name__ == '__main__':
    unittest.main()
